# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0  # use the latest stable prettier version
    hooks:
      - id: prettier
        additional_dependencies: ['prettier']
        files: "\\.(js|jsx|ts|tsx|json|css|scss|md|yml)$"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.31.0  # match your ESLint version
    hooks:
      - id: eslint
        additional_dependencies: ['eslint']
        files: "\\.(js|jsx|ts|tsx)$"